### ISSUE TITLE
Your online service seems not working?

### ISSUE THREAD

**Issue by markselby9** [Microsoft/ailab#1]
Sorry I don't know whether this is the right place to ask, but the online service of sketch2code: https://sketch2code.azurewebsites.net/ seems not working. I'm trying to upload a image but the browser gives me 500 error...And the page has no notification about this error.
![image](https://user-images.githubusercontent.com/3454734/44836617-ffebff00-ac69-11e8-8bd5-b4aa63f592f4.png)

**Comment by phillscirra** [comment]
Yes, same here.  Does the same in Chrome and Edge.

**Comment by ruidiasbraga** [comment]
Same here, after seeing the network log the server return a 500 error. the arguments brings the base64 original image but something is wrong when server reads it. 

Tried Microsoft support and they sent me to Azure Team support, on azure support they said it is not their site, so the only place I found to here is here.

Hope to have this fixed soon. Any need of help please contact me.

**Comment by jarnawer** [comment]
Seems it's working fine right now

**Comment by phillscirra** [comment]
Yeah, working here again too. Can now upload an image and it successfully interprets it.  Although, it's not entirely obvious how to download the html;  all I get is a .png file.

**Comment by jarnawer** [comment]
@phillscirra you can download it by clicking on "Download your Html" Button. It's a green button below the images, at the end of the prediction step

**Comment by ruidiasbraga** [comment]
Working now. ty.

**Comment by tarasha** [comment]
Hi Mark

I just noticed that it’s down too. Thanks for flagging. On it now.

Tara

Sent from my iPhone

On Aug 30, 2018, at 12:33 AM, Mark Feng <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry I don't know whether this is the right place to ask, but the online service of sketch2code: https://sketch2code.azurewebsites.net/<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsketch2code.azurewebsites.net%2F&data=02%7C01%7Ctarasha%40microsoft.com%7C6da8a1f00b4d4aaad9c208d60e4ae5de%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636712112184973826&sdata=vLCpdFyWKWSpETF82pPWg%2FkYox6hrGAq7LCLtdd6Ab0%3D&reserved=0> seems not working. I'm trying to upload a image but the browser gives me 500 error...And the page has no notification about this error.
[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3454734%2F44836617-ffebff00-ac69-11e8-8bd5-b4aa63f592f4.png&data=02%7C01%7Ctarasha%40microsoft.com%7C6da8a1f00b4d4aaad9c208d60e4ae5de%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636712112184973826&sdata=0O6j5xWLdiLbMKskaOpOM%2FNfeHSwtheibKEp%2BLPJE7E%3D&reserved=0>

**Comment by tarasha** [comment]
Just finished the testing. It’s working fine.
Please do flag any issues here or go to AI Lab where Sketch2Code is hosted and hit “contact us” you should be able to reach out directly to me over email.

The app tier is at large premium and we have enough capacity though the workload is 10 times higher during late nights PST.

Hope you all are enjoying Sketch2Code. Please keep updating us of whereabouts.

Tara

Sent from my iPhone

On Aug 30, 2018, at 5:37 AM, Rui Dias <notifications@github.com<mailto:notifications@github.com>> wrote:


Working now. ty.

**Comment by markselby9** [comment]
Yes it's working right now. Thank you!

**Comment by ruddhisundar** [comment]
The site is down, this is the first time I am trying to use it, I was curious but this thing is down.

**Comment by ruddhisundar** [comment]
Please get this online, asap. A sincere request!

**Comment by dmtzs** [comment]
Why is closed this? Is still down the page

**Comment by meyntony** [comment]
https://[sketch2code.azurewebsites.net](https://sketch2code.azurewebsites.net/)/ is this the official Website? Seems down for me aswell.

**Comment by somecoderithink** [comment]
Still down...
![image](https://github.com/microsoft/ailab/assets/87126175/c7f318fd-f2c8-4cc8-8cec-a6d945b8f4e8)
