### ISSUE TITLE
Could you support a well designed picture?

### ISSUE THREAD

**Issue by 1eeing** [Microsoft/ailab#10]
![-1 1](https://user-images.githubusercontent.com/20160126/45141068-6da6a680-b1e7-11e8-8bed-01df2e175554.png)
like this

**Comment by macastejon** [comment]
Sketch2Code is trained to work on handwritten designs so the results with real designs of photoshop images will be really poor

**Comment by duoduoObama** [comment]
Use a draft to draw out the basic framework, then fill in the area according to OK, is already perfect, liberating the front-end repetitive work ah! Nice author

**Comment by Dcatfly** [comment]
Why do you train handwritten pictures instead of real design drawings? @macastejon

**Comment by macastejon** [comment]
@Dcatfly we use handwritten because this is usually the first step we take when defining user interfaces and we always end up taking photos to a whiteboard and building some HTML from there. We wanted to build some to accelerate this process. Departing from real designs is the next step to take

**Comment by tarasha** [comment]
Closing the thread as we have answered the initial questions. Thanks for your feedback.
