### ISSUE TITLE
File missing from BackgroundMatting folder in VirtualStage?

### ISSUE THREAD

**Issue by superfluousIT** [microsoft/ailab#109]
bg_matting.py is referencing proportional_threshold but it doesn't seem to be part of the project. Based on naming conventions in project it seems like a proportional_threshold.py file is missing? Or is this imported from somewhere else?

-------------- from bg_matting.py: 
from proportional_threshold import proportional_split, proportional_merge
--------------

  File ".\bg_matting.py", line 9, in <module>
    from proportional_threshold import proportional_split, proportional_merge
ModuleNotFoundError: No module named 'proportional_threshold'

**Comment by lip-realmax** [comment]
Same issue.
@superfluousIT Do you have the solution yet?

```console
Traceback (most recent call last):
  File ".\bg_matting.py", line 9, in <module>
    from proportional_threshold import proportional_split, proportional_merge
ModuleNotFoundError: No module named 'proportional_threshold'
```

**Comment by chris-han** [comment]
Same here. There must be a proportional_threshold.py file missing.
