### ISSUE TITLE
Training question

### ISSUE THREAD

**Issue by jfpicard123** [Microsoft/ailab#16]
Quick question : who is responsible for training the model to detect/recognize patterns? Where is the "hey .. this is not a textbox but a dropdown" section?

Is that simply performed by Azure Cognitive Services or is it done anywhere in the code?

**Comment by macastejon** [comment]
That's a very good question!! Inside customvision.ai you can see all the images that users are submitting to the service and the predictions the actual model is generating. The perfect approach will be to take the most relevant pictures sent by users, tag them and retrain the model with this new data. This way we could be improving the system forever. That's the right approach for a commercial service.

**Comment by jfpicard123** [comment]
Wow! Thanks a lot for you answer!

**Comment by poush** [comment]
@macastejon in addition to this, can you also help me understand the dataset.json. I am confused about the dimension of "left", "right", "width" and "right". They clearly don't seem to be in pixels.

**Comment by macastejon** [comment]
Positions and dimensions in the dataset.json file are expressed in percentage relative to the total size of the image. So if the image is 1600 pixels width, a width or left of 0.5 means 800 pixels.

**Comment by tarasha** [comment]
Closing the issue as resolved
