### ISSUE TITLE
collaboration proposal

### ISSUE THREAD

**Issue by paulbrie** [Microsoft/ailab#2]
Hi, at https://teleporthq.io we're working on the same topic. 
https://twitter.com/TeleportHQio/status/1016341169662459904

We're able to export sketches in any type of code (React, React-Native, Vue, etc... )

We've partnered with https://moqups.com to test our technology in real-life conditions. We'd be really interested in starting a conversation about this topic. 

Best regards,
Paul

**Comment by arzounir** [comment]
Paul , looks very interesting how long we have to wait for the first release  ?

**Comment by tarasha** [comment]
Hey Paul

I am OOF until today 3rd September. Let’s certainly discuss this on my return tomorrow.

Thanks for your patience! Looking forward to speak with you.

Tara

Sent from my iPhone

On Aug 31, 2018, at 1:55 AM, Paul BRIE <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, at https://teleporthq.io<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fteleporthq.io&data=02%7C01%7Ctarasha%40microsoft.com%7C19409390f81d4e9e279e08d60f1f7803%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636713025162909976&sdata=bV4aM%2BGbHIT6DBGQTjjk%2F8lNYIPy2NxiYW%2FPQGuVZzI%3D&reserved=0> we're working on the same topic.
https://twitter.com/TeleportHQio/status/1016341169662459904<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FTeleportHQio%2Fstatus%2F1016341169662459904&data=02%7C01%7Ctarasha%40microsoft.com%7C19409390f81d4e9e279e08d60f1f7803%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636713025162909976&sdata=Q68PurTXB1czWrSfc8SAa%2BF21%2FAGiaIo2a4Xiez0%2BG0%3D&reserved=0>

We're able to export sketches in any type of code (React, React-Native, Vue, etc... )

We've partnered with https://moqups.com<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmoqups.com&data=02%7C01%7Ctarasha%40microsoft.com%7C19409390f81d4e9e279e08d60f1f7803%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636713025162909976&sdata=SEAEh14bXfecpBn0p55gAgq8uiH96IttPlalmRqXB7U%3D&reserved=0> to test our technology in real-life conditions. We'd be really interested in starting a conversation about this topic.

Best regards,
Paul

**Comment by paulbrie** [comment]
@tarasha: thanks for your reply. Ping me anytime, and I'll make myself available.

**Comment by paulbrie** [comment]
@arzounir: we're rolling out almost everything we have - OSS, experiments, (Sketch & AI), and our playground, by the end of October. You can follow our announcements here: https://twitter.com/teleporthqio

**Comment by tarasha** [comment]
Looks phenomenal. As you know Sketch2Code is an experiment, an idea, an inspiration for developers to do more with AI. It's not a product and it is indeed not our intention too. Can we please sync up and discuss your ideas. Please send and email invite to tarasha@microsoft.com. I shall send that further to Miguel

**Comment by paulbrie** [comment]
@tarasha: done!

**Comment by tarasha** [comment]
We had a great discussion, and closed the loop by discussing the issue over a call. Thanks to @macastejon Emil and you Paul
