### ISSUE TITLE
Any guidelines available for preparing sketch?

### ISSUE THREAD

**Issue by sirajrkhan** [Microsoft/ailab#42]
![testing-testers](https://user-images.githubusercontent.com/4670722/46594616-e1431880-caf1-11e8-8d6d-3a29b766de57.png)
![hand-sketch](https://user-images.githubusercontent.com/4670722/46594623-f1f38e80-caf1-11e8-8ea3-54f666eb76fc.jpg)

Hi There -- thanks for putting this up... Amazing concept.

I tried uploading attached sketch (both hand-sketch & from MSPaint) but the results were a little different. Is there a guideline for preparing the sketch?

Also, is this project in a state wherein it can be used in a real-world program? or it is at research-paper level?

Appreciate the response.

**Comment by tarasha** [comment]
This is just an idea to showcase ease of development with Microsoft AI. There's no specific guidelines for preparing the sketch, the model is a basic model and also has less iterations, hence the difference in results. Also, we have multiple projects with the base model and some of them have very limited iterations. We are working on pushing the model to cloud given, object detection now has a premium tier in Azure. Please add more src code and help this experiment grow further!
