### ISSUE TITLE
Sketch2Code sample model

### ISSUE THREAD

**Issue by Kagigz** [Microsoft/ailab#65]
Hi,

Would it be possible to update the README for Sketch2Code and explain how to train the sample model using the dataset provided? Is there a fast way of linking the tags in dataset.json to the images in our own Custom Vision project or do we have to manually tag them?

Thanks

**Comment by tarasha** [comment]
We recently released the AI School tutorial for Sketch2Code, which should help with all the questions you have for us here- https://aischool.microsoft.com/en-us/services/learning-paths/sketch2code/

**Comment by tarasha** [comment]
Closing the Issue as Resolved

**Comment by janmechtel** [comment]
I'd love to access the link above do you still have an archived version of it somewhere?
