### ISSUE TITLE
in 90deg,photo can not recognized

### ISSUE THREAD

**Issue by pandaiiz** [Microsoft/ailab#8]
in 90deg,photo can not recognized，and then it generate two boxes whth line

**Comment by macastejon** [comment]
you are right, it cannot detect if the provided image is rotated yet. It tries to understand your rotated image  as if it wasn't and that explain the bad results. Maybe this could be an interesting feature

**Comment by pandaiiz** [comment]
![282fa0079655309ff84ffbe1df85e4c](https://user-images.githubusercontent.com/25072780/45192902-d4769f00-b27d-11e8-9bf2-8960e97f65fc.png)
![f52b36d4bd8e324c83db03722c6b45e](https://user-images.githubusercontent.com/25072780/45192903-d4769f00-b27d-11e8-9712-863541cc5433.png)
haha,show you two photos,i think it need more data to learn
